vich_uploader:
    db_driver: orm

    mappings:
        Chambre:
            uri_prefix: /images/chambre
            upload_destination: '%kernel.project_dir%/public/images/chambre'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
